/* Auto-generated by genmsg_cpp for file /home/turtlebot/code/object_detection/object_detection_msgs/msg/Mask2D.msg */
#ifndef OBJECT_DETECTION_MSGS_MESSAGE_MASK2D_H
#define OBJECT_DETECTION_MSGS_MESSAGE_MASK2D_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace object_detection_msgs
{
template <class ContainerAllocator>
struct Mask2D_ {
  typedef Mask2D_<ContainerAllocator> Type;

  Mask2D_()
  : height(0)
  , width(0)
  , isValid()
  {
  }

  Mask2D_(const ContainerAllocator& _alloc)
  : height(0)
  , width(0)
  , isValid(_alloc)
  {
  }

  typedef uint32_t _height_type;
  uint32_t height;

  typedef uint32_t _width_type;
  uint32_t width;

  typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _isValid_type;
  std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  isValid;


  ROS_DEPRECATED uint32_t get_isValid_size() const { return (uint32_t)isValid.size(); }
  ROS_DEPRECATED void set_isValid_size(uint32_t size) { isValid.resize((size_t)size); }
  ROS_DEPRECATED void get_isValid_vec(std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other > & vec) const { vec = this->isValid; }
  ROS_DEPRECATED void set_isValid_vec(const std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other > & vec) { this->isValid = vec; }
private:
  static const char* __s_getDataType_() { return "object_detection_msgs/Mask2D"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "c073105a22d894f799b67a16c88b190a"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint32 height\n\
uint32 width\n\
bool[] isValid\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, height);
    ros::serialization::serialize(stream, width);
    ros::serialization::serialize(stream, isValid);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, height);
    ros::serialization::deserialize(stream, width);
    ros::serialization::deserialize(stream, isValid);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(height);
    size += ros::serialization::serializationLength(width);
    size += ros::serialization::serializationLength(isValid);
    return size;
  }

  typedef boost::shared_ptr< ::object_detection_msgs::Mask2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detection_msgs::Mask2D_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Mask2D
typedef  ::object_detection_msgs::Mask2D_<std::allocator<void> > Mask2D;

typedef boost::shared_ptr< ::object_detection_msgs::Mask2D> Mask2DPtr;
typedef boost::shared_ptr< ::object_detection_msgs::Mask2D const> Mask2DConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::object_detection_msgs::Mask2D_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::object_detection_msgs::Mask2D_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace object_detection_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::object_detection_msgs::Mask2D_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::object_detection_msgs::Mask2D_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::object_detection_msgs::Mask2D_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c073105a22d894f799b67a16c88b190a";
  }

  static const char* value(const  ::object_detection_msgs::Mask2D_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc073105a22d894f7ULL;
  static const uint64_t static_value2 = 0x99b67a16c88b190aULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detection_msgs::Mask2D_<ContainerAllocator> > {
  static const char* value() 
  {
    return "object_detection_msgs/Mask2D";
  }

  static const char* value(const  ::object_detection_msgs::Mask2D_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::object_detection_msgs::Mask2D_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint32 height\n\
uint32 width\n\
bool[] isValid\n\
\n\
";
  }

  static const char* value(const  ::object_detection_msgs::Mask2D_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::object_detection_msgs::Mask2D_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.height);
    stream.next(m.width);
    stream.next(m.isValid);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Mask2D_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detection_msgs::Mask2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::object_detection_msgs::Mask2D_<ContainerAllocator> & v) 
  {
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    s << indent << "isValid[]" << std::endl;
    for (size_t i = 0; i < v.isValid.size(); ++i)
    {
      s << indent << "  isValid[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.isValid[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECTION_MSGS_MESSAGE_MASK2D_H

